name: Tests
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          git clone https://github.com/pha4ge/primaschema.git
          python -m pip install ./primaschema
      - name: Validate all schemes
        run: |
          primaschema validate --recursive schemes
        env:
          PRIMASCHEMA_ROOT_PATH: ${{ github.workspace }}/primaschema
